#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="${WPS_VALIDATION_ENV_FILE:-$REPO_ROOT/.env.validation.local}"
ARTIFACT_ROOT="${WPS_VALIDATION_ARTIFACT_ROOT:-$REPO_ROOT/.scratch/wps-validation-environments}"
MINIMUM_FREE_KB=$((120 * 1024 * 1024))
TOTAL_STAGES=10

die() {
  warn "$1"
  exit 1
}

expand_path() {
  local value="$1"
  case "$value" in
    "~") printf '%s' "$HOME" ;;
    "~/"*) printf '%s/%s' "$HOME" "${value#~/}" ;;
    *) printf '%s' "$value" ;;
  esac
}

sha256_file() {
  shasum -a 256 "$1" | awk '{print $1}'
}

valid_ssh_target() {
  [[ "$1" =~ ^[A-Za-z0-9._-]+(@[A-Za-z0-9._-]+)?$ ]]
}

ssh_ready() {
  ssh -o BatchMode=yes -o ConnectTimeout=8 "$1" true >/dev/null 2>&1
}

require_arm64_value() {
  local value
  value=$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -d '\r')
  [[ "$value" == *arm64* || "$value" == *aarch64* ]]
}

require_python_39_value() {
  local value major minor
  value=$(printf '%s' "$1" | tr -d '\r')
  [[ "$value" =~ ^Python[[:space:]]+([0-9]+)\.([0-9]+)(\.|$) ]] || return 1
  major="${BASH_REMATCH[1]}"
  minor="${BASH_REMATCH[2]}"
  (( major > 3 || (major == 3 && minor >= 9) ))
}

banner "WPS local ARM64 validation environments"

stage "Host storage"
say "The two local VMs run one at a time and need a shared storage root with at least 120 GiB free."
[[ "$(uname -s)" == "Darwin" ]] || die "this wizard must run on macOS"
[[ "$(uname -m)" == "arm64" ]] || die "this wizard requires an Apple Silicon host"
ask VM_STORAGE_ROOT "VM storage directory (local or external disk):"
[[ -n "$VM_STORAGE_ROOT" ]] || VM_STORAGE_ROOT="$HOME/Virtual Machines.localized"
VM_STORAGE_ROOT=$(expand_path "$VM_STORAGE_ROOT")
if [[ ! -d "$VM_STORAGE_ROOT" ]]; then
  confirm "Create $VM_STORAGE_ROOT?" || die "storage directory was not created"
  mkdir -p "$VM_STORAGE_ROOT"
fi
available_kb=$(df -Pk "$VM_STORAGE_ROOT" | awk 'NR == 2 {print $4}')
[[ "$available_kb" =~ ^[0-9]+$ ]] || die "could not determine free storage"
if (( available_kb < MINIMUM_FREE_KB )); then
  available_gib=$((available_kb / 1024 / 1024))
  die "only ${available_gib} GiB is free; choose a location with at least 120 GiB"
fi
write_env VM_STORAGE_ROOT "$VM_STORAGE_ROOT"
mkdir -p "$ARTIFACT_ROOT"
note "Connection metadata stays in $ENV_FILE; it is ignored by Git."

stage "VMware Fusion"
say "VMware Fusion supplies native ARM64 virtualization on this Apple Silicon host."
if [[ ! -d "/Applications/VMware Fusion.app" ]]; then
  open_url "https://knowledge.broadcom.com/external/article/368667/download-and-license-vmware-desktop-hype.html"
  step "Sign in to Broadcom Support Portal and complete its trade-compliance form."
  step "Download VMware Fusion 26H1 or newer and install it in /Applications."
  step "Do not paste the Broadcom password into this wizard."
  pause "Press Enter after VMware Fusion is installed."
fi
[[ -d "/Applications/VMware Fusion.app" ]] || die "VMware Fusion was not found in /Applications"
note "Existing Fusion installations are reused."

stage "Fedora ARM64 VM"
existing_linux_vm=$(_existing LINUX_ARM_VM_BUNDLE || true)
if [[ -n "$existing_linux_vm" && -d "$existing_linux_vm" ]]; then
  LINUX_ARM_VM_BUNDLE="$existing_linux_vm"
  note "Reusing existing Linux VM: $LINUX_ARM_VM_BUNDLE"
else
  open_url "https://www.fedoraproject.org/workstation/download/"
  step "Under ARM aarch64, download the Fedora Workstation Live ISO and note its published SHA256."
  ask LINUX_ARM_ISO "Path to the downloaded Fedora aarch64 ISO:"
  LINUX_ARM_ISO=$(expand_path "$LINUX_ARM_ISO")
  [[ -f "$LINUX_ARM_ISO" ]] || die "Fedora ISO was not found"
  ask LINUX_ARM_ISO_SHA256 "Published Fedora ISO SHA256:"
  expected_linux_hash=$(printf '%s' "$LINUX_ARM_ISO_SHA256" | tr '[:upper:]' '[:lower:]')
  [[ "$expected_linux_hash" =~ ^[0-9a-f]{64}$ ]] || die "Fedora SHA256 must contain 64 hexadecimal characters"
  actual_linux_hash=$(sha256_file "$LINUX_ARM_ISO")
  [[ "$actual_linux_hash" == "$expected_linux_hash" ]] || die "Fedora ISO checksum does not match"
  write_env LINUX_ARM_ISO "$LINUX_ARM_ISO"
  write_env LINUX_ARM_ISO_SHA256 "$expected_linux_hash"
  step "In Fusion choose File → New → Install from disc or image, then select the verified ISO."
  step "Save the VM under $VM_STORAGE_ROOT with the name WPS-Linux-ARM64."
  step "Set 4 CPU cores, 4096 MB memory, a 40 GB virtual disk, and NAT networking."
  step "Install Fedora and create an ordinary account that can use sudo when prompted."
  pause "Press Enter after Fedora reaches its desktop."
  ask LINUX_ARM_VM_BUNDLE "Path to the WPS-Linux-ARM64.vmwarevm bundle:"
  LINUX_ARM_VM_BUNDLE=$(expand_path "$LINUX_ARM_VM_BUNDLE")
  [[ -d "$LINUX_ARM_VM_BUNDLE" ]] || die "Linux VM bundle was not found"
fi
write_env LINUX_ARM_VM_BUNDLE "$LINUX_ARM_VM_BUNDLE"

stage "Fedora access and Python"
existing_linux_target=$(_existing LINUX_ARM_SSH_TARGET || true)
if [[ -n "$existing_linux_target" ]] && valid_ssh_target "$existing_linux_target" && ssh_ready "$existing_linux_target"; then
  LINUX_ARM_SSH_TARGET="$existing_linux_target"
  note "Reusing reachable Linux SSH target from local state."
else
  step "Inside Fedora open Terminal."
  step "Run: sudo dnf install -y openssh-server python3 open-vm-tools"
  step "Run: sudo systemctl enable --now sshd"
  step "Run: hostname -I"
  ask LINUX_ARM_SSH_TARGET "Linux SSH target from this Mac (user@address or SSH alias):"
fi
valid_ssh_target "$LINUX_ARM_SSH_TARGET" || die "Linux SSH target contains unsupported characters"
linux_arch=$(ssh -o ConnectTimeout=15 "$LINUX_ARM_SSH_TARGET" uname -m | tr -d '\r')
require_arm64_value "$linux_arch" || die "Linux guest did not report ARM64/aarch64"
linux_python=$(ssh -o ConnectTimeout=15 "$LINUX_ARM_SSH_TARGET" 'python3 --version 2>&1' | tr -d '\r')
require_python_39_value "$linux_python" || die "Python 3.9 or newer was not found in the Linux guest"
write_env LINUX_ARM_SSH_TARGET "$LINUX_ARM_SSH_TARGET"
note "SSH passwords and key passphrases are handled by ssh and are never stored."

stage "Linux ARM64 WPS"
linux_wps_info=$(ssh "$LINUX_ARM_SSH_TARGET" "rpm -qa --qf '%{NAME}\t%{ARCH}\t%{VERSION}-%{RELEASE}\n' | grep -Ei '(^|-)wps' | head -n1" 2>/dev/null || true)
if require_arm64_value "$linux_wps_info"; then
  note "Reusing installed ARM64 WPS package: $linux_wps_info"
else
  open_url "https://365.wps.cn/download365"
  step "Choose WPS Office → Linux and download the current ARM64/aarch64 RPM."
  step "If there is no current ARM package, stop; do not use an x86 package or unofficial mirror."
  ask LINUX_ARM_WPS_PACKAGE "Path to the downloaded ARM64 WPS RPM on this Mac:"
  LINUX_ARM_WPS_PACKAGE=$(expand_path "$LINUX_ARM_WPS_PACKAGE")
  [[ -f "$LINUX_ARM_WPS_PACKAGE" ]] || die "Linux WPS package was not found"
  package_name=$(basename "$LINUX_ARM_WPS_PACKAGE")
  [[ "$package_name" =~ ^[A-Za-z0-9._-]+$ ]] || die "WPS package filename contains unsupported characters"
  scp "$LINUX_ARM_WPS_PACKAGE" "$LINUX_ARM_SSH_TARGET:/tmp/$package_name"
  package_arch=$(ssh "$LINUX_ARM_SSH_TARGET" "rpm -qp --qf '%{ARCH}' '/tmp/$package_name'" | tr -d '\r')
  require_arm64_value "$package_arch" || die "the selected Linux WPS package is not ARM64"
  confirm "Install the verified WPS RPM in the Linux VM?" || die "Linux WPS installation was declined"
  ssh -t "$LINUX_ARM_SSH_TARGET" "sudo dnf install -y '/tmp/$package_name'"
  linux_wps_info=$(ssh "$LINUX_ARM_SSH_TARGET" "rpm -qa --qf '%{NAME}\t%{ARCH}\t%{VERSION}-%{RELEASE}\n' | grep -Ei '(^|-)wps' | head -n1")
fi
step "In Fedora, launch WPS Writer, Spreadsheet, and Presentation once."
step "Confirm all three open as the ordinary user, then fully quit WPS."
pause "Press Enter after the Linux WPS launch check."

stage "Windows 11 ARM64 VM"
existing_windows_vm=$(_existing WINDOWS_ARM_VM_BUNDLE || true)
if [[ -n "$existing_windows_vm" && -d "$existing_windows_vm" ]]; then
  WINDOWS_ARM_VM_BUNDLE="$existing_windows_vm"
  note "Reusing existing Windows VM: $WINDOWS_ARM_VM_BUNDLE"
else
  open_url "https://www.microsoft.com/en-us/software-download/windows11arm64"
  step "In Fusion choose File → New → Get Windows from Microsoft."
  step "Choose Windows 11 Pro, download Windows, and keep UEFI firmware selected."
  step "Save the VM under $VM_STORAGE_ROOT with the name WPS-Windows-ARM64."
  step "Set 4 CPU cores, 8192 MB memory, an 80 GB virtual disk, NAT networking, and TPM 2.0."
  step "Complete setup. Enter a product key only inside Windows; this wizard never captures it."
  step "Open Settings → System → About and confirm System type says ARM-based processor."
  pause "Press Enter after Windows reaches its desktop and reports ARM64."
  ask WINDOWS_ARM_VM_BUNDLE "Path to the WPS-Windows-ARM64.vmwarevm bundle:"
  WINDOWS_ARM_VM_BUNDLE=$(expand_path "$WINDOWS_ARM_VM_BUNDLE")
  [[ -d "$WINDOWS_ARM_VM_BUNDLE" ]] || die "Windows VM bundle was not found"
fi
write_env WINDOWS_ARM_VM_BUNDLE "$WINDOWS_ARM_VM_BUNDLE"

stage "Windows access and Python"
existing_windows_target=$(_existing WINDOWS_ARM_SSH_TARGET || true)
if [[ -n "$existing_windows_target" ]] && valid_ssh_target "$existing_windows_target" && ssh_ready "$existing_windows_target"; then
  WINDOWS_ARM_SSH_TARGET="$existing_windows_target"
  note "Reusing reachable Windows SSH target from local state."
else
  open_url "https://www.python.org/downloads/windows/"
  step "Inside Windows install a supported Python 3 ARM64 build for the ordinary user."
  step "Enable Add python.exe to PATH in the Python installer."
  open_url "https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse"
  step "Open an elevated PowerShell."
  step 'Run: Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0'
  step 'Run: Start-Service sshd'
  step "Run: Set-Service -Name sshd -StartupType 'Automatic'"
  step 'Run: Get-NetIPAddress -AddressFamily IPv4 | Where-Object {$_.IPAddress -notlike "127.*"}'
  ask WINDOWS_ARM_SSH_TARGET "Windows SSH target from this Mac (user@address or SSH alias):"
fi
valid_ssh_target "$WINDOWS_ARM_SSH_TARGET" || die "Windows SSH target contains unsupported characters"
windows_arch=$(ssh -o ConnectTimeout=15 "$WINDOWS_ARM_SSH_TARGET" 'powershell.exe -NoProfile -Command "[Runtime.InteropServices.RuntimeInformation]::OSArchitecture"' | tr -d '\r')
require_arm64_value "$windows_arch" || die "Windows guest did not report ARM64"
windows_python=$(ssh -o ConnectTimeout=15 "$WINDOWS_ARM_SSH_TARGET" 'python --version 2>&1' | tr -d '\r')
require_python_39_value "$windows_python" || die "Python 3.9 or newer was not found in the Windows guest"
write_env WINDOWS_ARM_SSH_TARGET "$WINDOWS_ARM_SSH_TARGET"
note "Windows passwords and product keys are never written to local state."

stage "Windows ARM64 WPS"
open_url "https://bbs.wps.cn/topic/81703"
step "Inside Windows, use the page's WPS for Windows on ARM download link."
step "Install the ARM64/ARM64EC build; do not substitute the general x64 installer."
step "Launch Writer, Spreadsheet, and Presentation once."
step "In Task Manager → Details, enable the architecture/platform column if available and confirm WPS is ARM64."
ask WINDOWS_ARM_WPS_VERSION "WPS version shown by Help/About:"
[[ -n "$WINDOWS_ARM_WPS_VERSION" ]] || die "Windows WPS version is required"
write_env WINDOWS_ARM_WPS_VERSION "$WINDOWS_ARM_WPS_VERSION"
step "Fully quit WPS."
pause "Press Enter after native Windows ARM64 WPS is installed and closed."

stage "Snapshots and readiness"
say "Snapshots represent clean machines with WPS installed but no WPS Skill Add-in."
step "Shut down Fedora. In Fusion choose Virtual Machine → Snapshots and take clean-wps-before-addin."
step "Shut down Windows and take the same named snapshot."
step "Start both guests again, but keep WPS closed."
pause "Press Enter after both snapshots exist and both guests are running."

candidate_tmp=$(mktemp -d)
trap 'rm -rf "$candidate_tmp"' EXIT
candidate_archive="$candidate_tmp/wps-office.tgz"
tar -czf "$candidate_archive" -C "$REPO_ROOT/skills" wps-office
candidate_digest=$(sha256_file "$candidate_archive")
candidate_short="${candidate_digest:0:12}"
run_suffix="$(date -u +%Y%m%dT%H%M%SZ)"
linux_remote="wps-validation-$candidate_short-$run_suffix"
windows_remote="wps-validation-$candidate_short-$run_suffix"

scp "$candidate_archive" "$LINUX_ARM_SSH_TARGET:$linux_remote.tgz"
ssh "$LINUX_ARM_SSH_TARGET" "mkdir '$linux_remote' && tar -xzf '$linux_remote.tgz' -C '$linux_remote'"
scp "$candidate_archive" "$WINDOWS_ARM_SSH_TARGET:$windows_remote.tgz"
ssh "$WINDOWS_ARM_SSH_TARGET" "mkdir $windows_remote && tar -xzf $windows_remote.tgz -C $windows_remote"

confirm "Run first-use checks that install the Add-in into both VM profiles?" || die "Add-in installation was declined"
linux_first_check=$(ssh "$LINUX_ARM_SSH_TARGET" "cd '$linux_remote/wps-office' && python3 scripts/wps.py check" 2>&1 || true)
windows_first_check=$(ssh "$WINDOWS_ARM_SSH_TARGET" "cd $windows_remote\\wps-office && python scripts\\wps.py check" 2>&1 || true)
say "Linux first check: $linux_first_check"
say "Windows first check: $windows_first_check"
step "Fully start WPS in Fedora and leave one Writer document open."
step "Fully start WPS in Windows and leave one Writer document open."
pause "Press Enter after both Add-ins have started."
linux_final_check=$(ssh "$LINUX_ARM_SSH_TARGET" "cd '$linux_remote/wps-office' && python3 scripts/wps.py check" 2>&1 || true)
windows_final_check=$(ssh "$WINDOWS_ARM_SSH_TARGET" "cd $windows_remote\\wps-office && python scripts\\wps.py check" 2>&1 || true)
if printf '%s' "$linux_final_check" | grep -q '"ready":true'; then linux_readiness="ready"; else linux_readiness="failed"; fi
if printf '%s' "$windows_final_check" | grep -q '"ready":true'; then windows_readiness="ready"; else windows_readiness="failed"; fi
[[ "$linux_readiness" == "ready" ]] || warn "Linux readiness did not reach ready."
[[ "$windows_readiness" == "ready" ]] || warn "Windows readiness did not reach ready."

stage "Sanitized report"
report_file="$ARTIFACT_ROOT/preflight-$run_suffix.md"
{
  printf '# WPS validation environment preflight\n\n'
  printf -- '- Generated (UTC): %s\n' "$run_suffix"
  printf -- '- Candidate SHA256: %s\n\n' "$candidate_digest"
  printf '## Linux ARM64\n\n'
  printf -- '- Guest architecture: %s\n' "$linux_arch"
  printf -- '- Python: %s\n' "$linux_python"
  printf -- '- WPS package: %s\n' "$linux_wps_info"
  printf -- '- Add-in readiness: %s\n\n' "$linux_readiness"
  printf '## Windows ARM64\n\n'
  printf -- '- Guest architecture: %s\n' "$windows_arch"
  printf -- '- Python: %s\n' "$windows_python"
  printf -- '- WPS version: %s\n' "$WINDOWS_ARM_WPS_VERSION"
  printf -- '- WPS architecture: ARM64 confirmed in guest\n'
  printf -- '- Add-in readiness: %s\n\n' "$windows_readiness"
  printf '## Deferred targets\n\n'
  printf -- '- Linux x86_64: deferred; xianka is outside this wizard run\n'
  printf -- '- Windows x86_64: deferred\n'
} > "$report_file"
say "Sanitized report: $report_file"
note "The report contains no SSH target, username, password, product key, or Add-in credential."
if confirm "Publish this report as a comment on GitHub issue #20?"; then
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    gh issue comment 20 --repo JohnnyYwQ/wps-skills --body-file "$report_file"
  else
    SKIPPED+=("GitHub issue #20 comment")
    warn "gh is unavailable or unauthenticated; the local report is retained."
  fi
fi

finish
